name: screen.sbs-client-linux-deb
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

# build
      - name: Build client
        run: bash build-deb.sh $RELEASE_VERSION

# artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: build/screen-sbs*_all.deb


# release
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/screen-sbs*_all.deb
            