name: screen.sbs-client-linux-deb
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: install dependencies
        run: sudo apt-get install -y rpm
# build
      - name: Build client
        run: cd build && bash build.sh $RELEASE_VERSION

# artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: build/deb/screen-sbs*_all.deb

      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: build/rpm/RPMS/noarch/screen-sbs-*.noarch.rpm


# release
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/deb/screen-sbs*_all.deb
            build/rpm/RPMS/noarch/screen-sbs-*.noarch.rpm